import test from "node:test";
import assert from "node:assert/strict";
import { BehaviorRegistry, ComponentRegistry, HARDWARE_SCHEMA_VERSION, PROJECT_SCHEMA_VERSION, analog, createInstance, createSimulationRuntime, digital, digitalIndicator, digitalSource, logicalController, pwm, pwmActuator, relayBehavior, type ComponentBehavior, type CustomComponentDefinition, type EndpointFunction, type Project } from "../src/index.js";

const pins = [{id:"in",name:"IN",direction:"input" as const,capabilities:["gpio","digital-input","adc","pwm"] as const},{id:"out",name:"OUT",direction:"output" as const,capabilities:["gpio","digital-output","dac","pwm"] as const},{id:"control",name:"CONTROL",direction:"input" as const,capabilities:["gpio","digital-input"] as const},{id:"pwm",name:"PWM",direction:"input" as const,capabilities:["pwm"] as const}];
const definition=(id:string):CustomComponentDefinition=>({id:`sim.${id}`,schemaVersion:HARDWARE_SCHEMA_VERSION,kind:"custom",name:id,category:"test",electrical:{},pins,interfaces:[]});
const registry=new ComponentRegistry().registerAll(["source","controller","led","relay","motor","custom","broken","missing"].map(definition));
const ep=(instanceId:string,endpointId:string,fn:EndpointFunction)=>({instanceId,endpointKind:"pin" as const,endpointId,function:fn});
function project(instances:[string,string,string?][],nets:{id:string;type:"digital"|"analog"|"pwm";ends:ReturnType<typeof ep>[];delay?:number}[]):Project{return {schemaVersion:PROJECT_SCHEMA_VERSION,id:"p",name:"P",createdAt:"x",updatedAt:"x",instances:instances.map(([id,def,behavior])=>({...createInstance(id,`sim.${def}`,id),...(behavior?{configuration:{behaviorId:behavior}}:{})})),nets:nets.map(n=>({id:n.id,projectId:"p",name:n.id,domain:"physical",type:n.type,enabled:true,endpoints:n.ends,...(n.delay===undefined?{}:{configuration:{propagationDelayMs:n.delay}})}))};}
const behaviors=()=>new BehaviorRegistry().register("sim.source",()=>digitalSource()).register("sim.led",()=>digitalIndicator()).register("sim.relay",()=>relayBehavior()).register("sim.motor",()=>pwmActuator()).register("sim.controller",()=>logicalController([{output:"out",value:{input:"in"}}]));

test("runtime initialization, clock, scheduling, and immutable snapshot",()=>{const r=createSimulationRuntime(project([["s","source"]],[]),registry,behaviors());r.initialize();assert.equal(r.time,0);r.scheduleInput("s",digital("HIGH"),100);r.runUntil(99);assert.equal(r.time,99);r.runUntil(100);assert.equal(r.getComponentState("s")?.outputs.out?.kind,"digital");const snap=r.getSnapshot();assert.equal(snap.simulationTime,100);assert.throws(()=>r.runUntil(99));});
test("same timestamp uses stable insertion ordering",()=>{const r=createSimulationRuntime(project([["s","source"]],[]),registry,behaviors());r.scheduleInput("s",digital("HIGH"),5);r.scheduleInput("s",digital("LOW"),5);r.runUntil(5);assert.deepEqual(r.getComponentState("s")?.outputs.out,digital("LOW"));const inputs=r.getEventLog().filter(e=>e.type==="external-input");assert.ok(inputs[0]!.sequence<inputs[1]!.sequence);});
test("digital sensor through controller to LED",()=>{const p=project([["s","source"],["c","controller"],["l","led"]],[{id:"a",type:"digital",ends:[ep("s","out","digital-output"),ep("c","in","digital-input")]},{id:"b",type:"digital",ends:[ep("c","out","digital-output"),ep("l","in","digital-input")]}]);const r=createSimulationRuntime(p,registry,behaviors());r.scheduleInput("s",digital("HIGH"),100);r.runUntil(100);assert.equal(r.getComponentState("l")?.state.on,true);});
test("analog threshold drives relay",()=>{const b=behaviors().register("threshold",()=>logicalController([{output:"out",value:{op:"gt",left:{input:"in"},right:{constant:{kind:"data",value:2}}}}]));const p=project([["s","source"],["c","controller","threshold"],["r","relay"]],[{id:"a",type:"analog",ends:[ep("s","out","analog-output"),ep("c","in","analog-input")]},{id:"b",type:"digital",ends:[ep("c","out","digital-output"),ep("r","control","digital-input")]}]);const r=createSimulationRuntime(p,registry,b);r.scheduleInput("s",analog(2.1),0);r.runUntil(0);assert.equal(r.getComponentState("r")?.state.energized,true);});
test("PWM propagates to normalized motor command",()=>{const p=project([["s","source"],["m","motor"]],[{id:"pwm",type:"pwm",ends:[ep("s","out","pwm"),ep("m","pwm","pwm")]}]);const r=createSimulationRuntime(p,registry,behaviors());r.scheduleInput("s",pwm(.65,500),0);r.runUntil(0);assert.equal(r.getComponentState("m")?.state.speedCommand,.65);});
test("one-to-many and propagation delay",()=>{const p=project([["s","source"],["a","led"],["b","led"]],[{id:"n",type:"digital",delay:25,ends:[ep("s","out","digital-output"),ep("a","in","digital-input"),ep("b","in","digital-input")]}]);const r=createSimulationRuntime(p,registry,behaviors());r.scheduleInput("s",digital("HIGH"),10);r.runUntil(34);assert.equal(r.getComponentState("a")?.state.on,false);r.runUntil(35);assert.equal(r.getComponentState("a")?.state.on,true);assert.equal(r.getComponentState("b")?.state.on,true);});
test("unchanged signal settles and reset exactly reinitializes",()=>{const p=project([["s","source"],["l","led"]],[{id:"n",type:"digital",ends:[ep("s","out","digital-output"),ep("l","in","digital-input")]}]);const r=createSimulationRuntime(p,registry,behaviors());r.scheduleInput("s",digital("LOW"),0);r.runUntil(0);const first=r.getSnapshot();assert.equal(first.pendingEventCount,0);r.reset();r.runUntil(0);assert.deepEqual(r.getSnapshot().componentStates,first.componentStates);});
test("missing behavior and malformed signals are diagnostics",()=>{const r=createSimulationRuntime(project([["x","missing"]],[]),registry,behaviors());r.initialize();assert.ok(r.getDiagnostics().some(d=>d.code==="UNRESOLVED_BEHAVIOR"));const r2=createSimulationRuntime(project([["s","source"]],[]),registry,behaviors());r2.scheduleInput("s",{kind:"pwm",dutyCycle:4,frequencyHz:1} as never,0);r2.runUntil(0);assert.ok(r2.getDiagnostics().some(d=>d.code==="INVALID_RUNTIME_SIGNAL"));});
test("behavior exceptions are isolated",()=>{const b=behaviors().register("boom",()=>({initialize(){throw new Error("boom");}}));const r=createSimulationRuntime(project([["x","broken","boom"]],[]),registry,b);r.initialize();assert.ok(r.getDiagnostics().some(d=>d.code==="BEHAVIOR_EXCEPTION"));});
test("feedback oscillation is bounded",()=>{const toggle:ComponentBehavior={evaluate(ctx){const v=ctx.readInput("in");ctx.drive("out",digital(v?.kind==="digital"&&v.level==="HIGH"?"LOW":"HIGH"));}};const b=behaviors().register("toggle",()=>toggle);const p=project([["x","custom","toggle"]],[{id:"loop",type:"digital",ends:[ep("x","out","digital-output"),ep("x","in","digital-input")]}]);const r=createSimulationRuntime(p,registry,b,{maxEventsAtSameTime:20});r.scheduleEvent(0,"drive-output","x:pin:out",digital("LOW"));r.runUntil(0);assert.ok(r.getDiagnostics().some(d=>d.code==="SIMULATION_OSCILLATION"));});
test("identical replay, multiple instances, custom behaviors and multi-controller chain",()=>{const passthrough=()=>logicalController([{output:"out",value:{input:"in"}}]);const b=behaviors().register("pass",passthrough);const p=project([["s","source"],["c1","custom","pass"],["c2","custom","pass"],["l1","led"],["l2","led"]],[{id:"n1",type:"digital",ends:[ep("s","out","digital-output"),ep("c1","in","digital-input")]},{id:"n2",type:"digital",ends:[ep("c1","out","digital-output"),ep("c2","in","digital-input"),ep("l1","in","digital-input")]},{id:"n3",type:"digital",ends:[ep("c2","out","digital-output"),ep("l2","in","digital-input")]}]);const run=()=>{const r=createSimulationRuntime(p,registry,b);r.scheduleInput("s",digital("HIGH"),7);r.runUntil(7);return {snapshot:r.getSnapshot(),log:r.getEventLog()};};assert.deepEqual(run(),run());assert.equal(run().snapshot.componentStates.l1?.state.on,true);assert.equal(run().snapshot.componentStates.l2?.state.on,true);});
test("virtual time stays monotonic and invalid propagation delay is contained",()=>{const r=createSimulationRuntime(project([["s","source"]],[]),registry,behaviors());r.runUntil(10);assert.throws(()=>r.scheduleInput("s",digital("HIGH"),9),RangeError);assert.throws(()=>r.scheduleEvent(9,"custom"),RangeError);assert.throws(()=>r.runUntil(Number.NaN),RangeError);const p=project([["s","source"],["l","led"]],[{id:"n",type:"digital",delay:-1,ends:[ep("s","out","digital-output"),ep("l","in","digital-input")]}]);const delayed=createSimulationRuntime(p,registry,behaviors());delayed.scheduleInput("s",digital("HIGH"),0);delayed.runUntil(0);assert.equal(delayed.time,0);assert.ok(delayed.getDiagnostics().some(d=>d.code==="INVALID_PROPAGATION_DELAY"));});
