import type { Project, EndpointRef } from "../domain/types.js";
import type { ComponentRegistry } from "../hardware/registry.js";
import { BehaviorRegistry } from "./behaviors.js";
import { DeterministicScheduler } from "./scheduler.js";
import { endpointKey, type BehaviorContext, type ComponentBehavior, type ComponentRuntimeSnapshot, type DiagnosticSeverity, type LogicalValue, type RuntimeLogEntry, type SignalValue, type SimulationDiagnostic, type SimulationEvent, type SimulationOptions, type SimulationSnapshot } from "./types.js";
import { isSignalValue, signalEquals } from "./signals.js";

interface MutableComponent { state: Record<string, LogicalValue>; inputs: Map<string, SignalValue>; outputs: Map<string, SignalValue>; behavior?: ComponentBehavior }
const clone = <T>(value: T): T => structuredClone(value);

/** Headless, synchronous discrete-event runtime. Project/catalog objects are read, never mutated. */
export class SimulationRuntime {
  readonly #project: Project; readonly #registry: ComponentRegistry; readonly #behaviors: BehaviorRegistry; readonly #options: Required<SimulationOptions>;
  #scheduler = new DeterministicScheduler(); #components = new Map<string, MutableComponent>(); #endpointValues = new Map<string, SignalValue>(); #netValues = new Map<string, SignalValue>();
  #endpointNets = new Map<string, string[]>(); #netDrivers = new Map<string, Map<string, SignalValue>>(); #diagnostics: SimulationDiagnostic[]=[]; #log: RuntimeLogEntry[]=[]; #logSequence=0; #time=0; #status: "ready"|"running"|"paused"="ready"; #initialized=false;
  constructor(project: Project, registry: ComponentRegistry, behaviors: BehaviorRegistry, options: SimulationOptions={}) { this.#project=project;this.#registry=registry;this.#behaviors=behaviors;this.#options={maxEventsPerRun:options.maxEventsPerRun??100_000,maxEventsAtSameTime:options.maxEventsAtSameTime??10_000,eventLogRetention:options.eventLogRetention??10_000,defaultPropagationDelayMs:options.defaultPropagationDelayMs??0}; }
  get time(): number { return this.#time; }
  initialize(): void {
    if(this.#initialized)return; this.#build(); this.#initialized=true; this.#record("SIMULATION_STARTED","Simulation initialized");
    for(const instance of this.#project.instances.filter(i=>i.enabled).sort((a,b)=>a.id.localeCompare(b.id))) this.#invoke(instance.id,"initialize");
  }
  reset(): void { this.#scheduler.clear();this.#components.clear();this.#endpointValues.clear();this.#netValues.clear();this.#endpointNets.clear();this.#netDrivers.clear();this.#diagnostics=[];this.#log=[];this.#logSequence=0;this.#time=0;this.#status="ready";this.#initialized=false;this.initialize(); }
  pause(): void { this.#status="paused"; this.#record("SIMULATION_PAUSED","Simulation paused"); }
  resume(): void { this.#status="ready"; this.#record("SIMULATION_RESUMED","Simulation resumed"); }
  setInput(instanceId:string,value:SignalValue,atTime=this.#time): string { return this.scheduleInput(instanceId,value,atTime); }
  scheduleInput(instanceId:string,value:SignalValue,atTime:number): string { this.#ensure(); const event=this.#scheduler.schedule({time:atTime,type:"external-input",target:instanceId,payload:clone(value),priority:10,source:"external"});return event.id; }
  scheduleEvent(time:number,type:SimulationEvent["type"],target?:string,payload?:unknown,priority=100):string {this.#ensure();return this.#scheduler.schedule({time,type,priority,...(target?{target}:{}),...(payload===undefined?{}:{payload})}).id;}
  step(): boolean { this.#ensure(); if(this.#status==="paused")return false; const event=this.#scheduler.pop();if(!event)return false;this.#status="running";this.#time=event.time;this.#process(event);this.#status="ready";return true; }
  stepOnce(): boolean { return this.step(); }
  runUntil(until:number): void { this.#ensure();if(until<this.#time)throw new RangeError("Cannot run backwards in simulation time");if(this.#status==="paused")return;let count=0,same=0,last=-1;while(this.#scheduler.peek()&&this.#scheduler.peek()!.time<=until){const next=this.#scheduler.peek()!;same=next.time===last?same+1:1;last=next.time;if(++count>this.#options.maxEventsPerRun){this.#diag("SIMULATION_EVENT_LIMIT","Event limit reached","error");break;}if(same>this.#options.maxEventsAtSameTime){this.#diag("SIMULATION_OSCILLATION","Same-time propagation did not settle","error");this.#discardTime(next.time);break;}this.step();}this.#time=until; }
  getComponentState(id:string):ComponentRuntimeSnapshot|undefined {const c=this.#components.get(id);return c?{state:clone(c.state),inputs:Object.fromEntries([...c.inputs].map(([k,v])=>[k,clone(v)])),outputs:Object.fromEntries([...c.outputs].map(([k,v])=>[k,clone(v)]))}:undefined;}
  getEndpointValue(ref:EndpointRef|string):SignalValue|undefined {const v=this.#endpointValues.get(typeof ref==="string"?ref:endpointKey(ref));return v&&clone(v);}
  getNetValue(id:string):SignalValue|undefined {const v=this.#netValues.get(id);return v&&clone(v);}
  getDiagnostics():readonly SimulationDiagnostic[]{return clone(this.#diagnostics);}
  getEventLog():readonly RuntimeLogEntry[]{return clone(this.#log);}
  getSnapshot():SimulationSnapshot {const states:Record<string,ComponentRuntimeSnapshot>={};for(const id of [...this.#components.keys()].sort())states[id]=this.getComponentState(id)!;return {simulationTime:this.#time,status:this.#status,componentStates:states,endpointValues:Object.fromEntries([...this.#endpointValues].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,clone(v)])),netValues:Object.fromEntries([...this.#netValues].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,clone(v)])),pendingEventCount:this.#scheduler.size,diagnostics:this.getDiagnostics()};}
  #ensure(){if(!this.#initialized)this.initialize();}
  #build(){for(const net of this.#project.nets.filter(n=>n.enabled).sort((a,b)=>a.id.localeCompare(b.id)))for(const ep of net.endpoints){const key=endpointKey(ep);const list=this.#endpointNets.get(key)??[];list.push(net.id);this.#endpointNets.set(key,list);}for(const instance of this.#project.instances.filter(i=>i.enabled).sort((a,b)=>a.id.localeCompare(b.id))){const definition=this.#registry.get(instance.definitionId);const runtime:MutableComponent={state:{},inputs:new Map(),outputs:new Map()};this.#components.set(instance.id,runtime);if(!definition){this.#diag("MISSING_DEFINITION",`Definition '${instance.definitionId}' is unavailable`,"error",instance.id);continue;}const behaviorId=typeof instance.configuration?.behaviorId==="string"?instance.configuration.behaviorId:instance.definitionId;const factory=this.#behaviors.get(behaviorId);if(!factory){this.#diag("UNRESOLVED_BEHAVIOR",`No behavior registered as '${behaviorId}'`,"warning",instance.id);continue;}try{runtime.behavior=factory(instance,definition);}catch(error){this.#behaviorError(instance.id,error);}}}
  #process(event:SimulationEvent){this.#record(event.type,`${event.type}${event.target?` for ${event.target}`:""}`,event);if(event.type==="drive-output"){this.#driveNow(event.target!,event.payload);return;}if(event.type==="endpoint-changed"){const [instanceId,,endpointId]=event.target!.split(":");const c=this.#components.get(instanceId!);if(c&&isSignalValue(event.payload)){c.inputs.set(endpointId!,clone(event.payload));this.#invoke(instanceId!,"evaluate",endpointId);}return;}if(event.target)this.#invoke(event.target,"event",undefined,event);}
  #driveNow(target:string,payload:unknown){if(!isSignalValue(payload)){this.#diag("INVALID_RUNTIME_SIGNAL",`Invalid signal driven at '${target}'`,"error",target.split(":")[0],undefined,target);return;}const [instanceId,,endpointId]=target.split(":");const c=this.#components.get(instanceId!);if(!c)return;if(signalEquals(c.outputs.get(endpointId!),payload))return;c.outputs.set(endpointId!,clone(payload));this.#endpointValues.set(target,clone(payload));this.#record("OUTPUT_CHANGED",`${target} changed`,undefined,target,payload);
    for(const netId of this.#endpointNets.get(target)??[]){const net=this.#project.nets.find(n=>n.id===netId)!;const drivers=this.#netDrivers.get(netId)??new Map<string,SignalValue>();drivers.set(target,clone(payload));this.#netDrivers.set(netId,drivers);const values=[...drivers.values()];if(values.some(v=>!signalEquals(v,values[0]))){this.#diag("DRIVER_CONFLICT",`Net '${netId}' has conflicting drivers`,"error",instanceId,netId,target);continue;}if(signalEquals(this.#netValues.get(netId),payload))continue;this.#netValues.set(netId,clone(payload));this.#record("NET_CHANGED",`${netId} changed`,undefined,netId,payload);const configured=(net.configuration as Record<string,unknown>|undefined)?.propagationDelayMs;const delay=typeof configured==="number"?configured:this.#options.defaultPropagationDelayMs;for(const endpoint of net.endpoints){const key=endpointKey(endpoint);if(key===target)continue;if(signalEquals(this.#endpointValues.get(key),payload))continue;this.#endpointValues.set(key,clone(payload));this.#scheduler.schedule({time:this.#time+delay,type:"endpoint-changed",target:key,payload:clone(payload),priority:30,source:netId});}}
  }
  #invoke(instanceId:string,kind:"initialize"|"evaluate"|"event",endpoint?:string,event?:SimulationEvent){const instance=this.#project.instances.find(i=>i.id===instanceId);const definition=instance&&this.#registry.get(instance.definitionId);const runtime=this.#components.get(instanceId);if(!instance||!definition||!runtime?.behavior)return;const context=this.#context(instanceId);try{if(kind==="initialize")runtime.behavior.initialize?.(context);else if(kind==="evaluate")runtime.behavior.evaluate?.(context,endpoint);else if(event)runtime.behavior.onEvent?.(context,event);}catch(error){this.#behaviorError(instanceId,error);}}
  #context(instanceId:string):BehaviorContext {const instance=this.#project.instances.find(i=>i.id===instanceId)!;const definition=this.#registry.require(instance.definitionId);const runtime=this.#components.get(instanceId)!;return {instance,definition,time:this.#time,readInput:id=>{const v=runtime.inputs.get(id);return v&&clone(v);},readState:key=>clone(runtime.state[key]),setState:(key,value)=>{if(JSON.stringify(runtime.state[key])===JSON.stringify(value))return;runtime.state[key]=clone(value);this.#record("COMPONENT_STATE_CHANGED",`${instanceId}.${key} changed`,undefined,instanceId);},drive:(id,value,delay=0)=>this.#scheduler.schedule({time:this.#time+delay,type:"drive-output",target:`${instanceId}:pin:${id}`,payload:clone(value),priority:20,source:instanceId}),schedule:(delay,type,payload)=>this.#scheduler.schedule({time:this.#time+delay,type,target:instanceId,...(payload===undefined?{}:{payload}),priority:40,source:instanceId}),diagnostic:(code,message,severity="warning")=>this.#diag(code,message,severity,instanceId)};}
  #diag(code:string,message:string,severity:DiagnosticSeverity,componentId?:string,netId?:string,endpoint?:string){this.#diagnostics.push({code,message,severity,time:this.#time,...(componentId?{componentId}:{}),...(netId?{netId}:{}),...(endpoint?{endpoint}:{})});this.#record("DIAGNOSTIC",`${code}: ${message}`);}
  #behaviorError(id:string,error:unknown){this.#diag("BEHAVIOR_EXCEPTION",`Behavior failed: ${error instanceof Error?error.message:String(error)}`,"error",id);}
  #record(type:string,message:string,event?:SimulationEvent,target?:string,value?:SignalValue){this.#log.push({sequence:this.#logSequence++,time:this.#time,type,message,...(event?{eventId:event.id,target:event.target}:{}),...(target?{target}:{}),...(value?{value:clone(value)}:{})});if(this.#log.length>this.#options.eventLogRetention)this.#log.splice(0,this.#log.length-this.#options.eventLogRetention);}
  #discardTime(time:number){while(this.#scheduler.peek()?.time===time)this.#scheduler.pop();}
}
export function createSimulationRuntime(project:Project,registry:ComponentRegistry,behaviors:BehaviorRegistry,options?:SimulationOptions):SimulationRuntime{return new SimulationRuntime(project,registry,behaviors,options);}
